### ISSUE TITLE
model_matrix.plm for RE models

### ISSUE THREAD

**Issue by helix123** [jepusto/clubSandwich#14]
Could you check please: in model_matrix.plm for RE models, the model matrix is extracted by:
`model.matrix(Formula::as.Formula(formula(obj)), model.frame(obj))`

This will give the untransformed data (as it is in the model frame) - intended? What is the reason behind the special treatment of RE models here?

**Comment by jepusto** [comment]
I do it this way because the adjustment matrices involve the quantities (X_i' W_i) for i = 1...m, where m is the number of clusters, X_i is the untransformed design matrix for cluster i, and W_i is the weight matrix for cluster i. For the RE model, W_i is the inverse of the estimated variance matrix of y_i. The transformed design matrix corresponds to X_i' W_i^(1/2), so not a convenient form for my purposes.
