### ISSUE TITLE
"CR1" Formula

### ISSUE THREAD

**Issue by wviechtb** [jepusto/clubSandwich#22]
Shouldn't the adjustment factor for "CR1" be `m / (m - p)`, where `m` is the number of clusters and `p` the rank of the model matrix (instead of `m / (m - 1)`)? This would be analogous to 'HC1'. See, for example, MacKinnon and White (1985).

**Comment by jepusto** [comment]
We use the definition from [Cameron and Miller (2015, p. 9)](http://old.econ.ucdavis.edu/faculty/cameron/research/Cameron_Miller_JHR_2014_July_09.pdf). There's not a clear right answer even for very simple cases because the degree of bias depends on whether the predictors are identified within each cluster or between clusters:

- If you've got all between-cluster predictors (no within-cluster variation), then `m / (m - p)` will be a closer approximation. 
- If the predictor of interest is identified within each cluster, then the CRVE is roughly the sample variance of the cluster-specific slope estimates, in which case `m / (m - 1)` will be a closer approximation. 

But I think the take-away is clear: CR1 (either version) doesn't account for the fact that the degree of bias adjustment depends on the structure of the predictors. Better to use CR2, which takes these features into account, instead.

**Comment by wviechtb** [comment]
I agree that CR2 is better. I was just comparing results from `clubSandwich` with `robust()` from `metafor`, where I use `m / (m - p)` by default. One can set `adjust = "Stata2"`, which then uses `m / (m - 1)`, but this is currently undocumented (and `adjust = "Stata1"` which is the same as CR1S, but see issue #23). Would you mind adding `m / (m - p)` as another option (as `CR1<?>`)?

**Comment by jepusto** [comment]
I guess I could add "CR1p" that uses the factor m / (m - p). Is the rationale just compatibility/comparability with metafor?

**Comment by wviechtb** [comment]
> Is the rationale just compatibility/comparability with metafor?

Indeed. Thanks for considering.
