### ISSUE TITLE
A more informative error message for missing data?

### ISSUE THREAD

**Issue by heinonmatti** [jepusto/clubSandwich#31]
Hi! 

Noticed this thing, which caused a bit of trouble. Could we maybe have a more informative message saying that you can't have missings, or maybe build in a way to deal with them?

This gives "Error in t(x) %*% w : non-conformable arguments":
---------------------------------------------------------------
data <- data.frame(value = rnorm(500, mean = 100, sd = 10), 
                   cluster = sample(c(letters[1:10], NA), 500, replace = TRUE))

lm_object <- lm(value ~ 1, data = data)
clubSandwich::vcovCR(lm_object, cluster = data$cluster, type = "CR1S")

Removing NA helps:
---------------------------------------------------------------
data <- data.frame(value = rnorm(500, mean = 100, sd = 10), 
                   cluster = sample(c(letters[1:10], NA), 500, replace = TRUE)) **%>% 
  na.omit()**

lm_object <- lm(value ~ 1, data = data)

clubSandwich::vcovCR(lm_object, cluster = data$cluster, type = "CR1S")

**Comment by jepusto** [comment]
Thanks for documenting this. I'll add a better error message. (It won't work to drop observations with missing values for the clustering variable because that would potentially require re-fitting the model that is passed in to vcovCR.)

**Comment by jflournoy** [comment]
Related to this, in case it's helpful, I noticed that for lme models, using `na.action=na.omit` works fine but `na.exclude` throws the above error. At least for lme, I traced this to `clubSandwich:::targetVariance.lme` line 38 `Z_mat <- model.matrix(obj$modelStruct$reStruc, getData(obj))`, where `getData(obj)` returns the data without NA rows removed. This is admittedly a very narrow case for throwing the error, but I think it could be solved by replacing the getData call with something like `getData(obj)[-obj$na.action, ]` if the class of na.action is "exclude". 

So instead of `Z_mat <- model.matrix(obj$modelStruct$reStruc, getData(obj))`,

```
if(inherits(obj$na.action, "exclude")){
    obj_data <- getData(obj)[-obj$na.action, ]
} else {
    obj_data <- getData(obj)
}
Z_mat <- model.matrix(obj$modelStruct$reStruc, getData(obj))
```
