### ISSUE TITLE
Error: cannot allocate vector of size 1.4 Gb

### ISSUE THREAD

**Issue by niguarino** [jepusto/clubSandwich#72]
I am trying to use both the `survey` and `clubSandwich` packages to estimate a regression using complex survey data. I am doing this because I have reshaped the complex survey data such that each student has two observations (one at each time point) and want to estimate clustered robust standard errors. After applying the `survey` package to estimate my linear model, I was able to successfully develop a variance-covariance matrix using `vcovCR()` in `clubSandwich`, setting the cluster by student ID and `type = "CR2"` as suggested. When I run `conf_int()`, however, I get this message:

`Error: cannot allocate vector of size 1.4 Gb`

Do you know why I could be receiving this message? I have several thousand students in the data. Is it possible that this is causing the issue? Do you have any suggestions for fixing this issue?

Thank you for your help.

**Comment by jepusto** [comment]
I would guess that the error occurs because you are working with a very large dataset with some very large clusters in it. But the broader issue is that clubSandwich does not support models estimated with the survey package. (The default methods might work but I have not tested them.) The survey package has its own implementation of cluster-robust standard errors, I would suggest trying as the first course of action.

**Comment by niguarino** [comment]
That sounds great. Thank you very much!
