### ISSUE TITLE
break up bread and meat?

### ISSUE THREAD

**Issue by benthestatistician** [jepusto/clubSandwich#9]
Hi @jepusto, 

@josherrickson and I were wondering,  does `clubSandwich` have a route to/user-facing mechanism for calculating meat only, ie assuming the user will construct his or her own bread matrix or get it from elsewhere?  For us something like that would be pretty nifty.

Cool project! --ben

**Comment by jepusto** [comment]
Hi Ben, thanks for the suggestion. Are y'all on some sort of paleo diet or just gluten sensitive? 

Currently `clubSandwich` only has a vcovCR method, which computes the bread matrix internally. It probably wouldn't too hard to add a meat-only option, along the lines of 
'vcovCR(obj, cluster, type, bread, target, inverse_var)` 
where `bread` could be a matrix or an arbitrary function, or would be computed internally if NULL. 

Could y'all add one or more use cases to show me why this option would be useful?

**Comment by benthestatistician** [comment]
>  y'all on some sort of paleo diet or just gluten sensitive

(snort)  

We're looking to use it to get SEs for stacked estimating equations, cf e.g. Appendix Sec 6.6. of the Carroll et al measurement error book (2006). For this we would need the meat, rather than an option to pass our own bread.  It's sort of the opposite of gluten-sensitivity -- we're not going to do without bread, rather we're going to build an elaborate quintuple-decker sandwich with four or five slices of bread (two of them custom-baked) tucked in.

**Comment by jepusto** [comment]
To clarify, the clubSandwich estimators have the following form:

V = B (\sum_{g=1}^G D_g r_g r_g' D_g') B,

where
- B is the bread
- r_g is the vector of residuals from cluster g
- D_g is an n_g \times p matrix that involves the design matrix for cluster g (X_g), weight matrix for cluster g (W_g), and potentially also small-sample corrections to the residuals. For CR0, D_g = X_g'W_g. For CR2 D_g = X_g' W_g A_g, where A_g is an n_g \times n_g adjustment matrix chosen so that D_g r_g r_g' D_g is exactly unbiased under a working model. 

To your question, do I understand correctly that you need the meat from each cluster, as in the G \times p matrix 

{D_g r_g}_{g=1}^G

? Or just the D_g's? 

To make this work for stacked estimating equations, are you imagining calculating the small-sample adjustments separately for each component model?

**Comment by benthestatistician** [comment]
thanks for the clarifier, James.  To answer your questions:
1.  We'd just need the $\sum_{g=1}^G D_g r_g r_g' D_g'$, not the cluster-wise contributions. 
2. I'm not sure what we'd do for small-sample adjustments; that's somewhat an open topic.  In some scenarios it won't matter much.  In some others that @josherrickson has been exploring in his dissertation it does matter; in those cases he's been  using something similar to your `type = "CR1S"` for at least one stage of the calculation. Your package could be useful to me whether or not we get access to all of the small-sample adjustments you've been cooking up. 
3.  (Sorry for slow reply - I had written this the day after you wrote, only seeing now that I forgot to post it.)

**Comment by jepusto** [comment]
Got it. I can add this, though probably will not get to it until after JSM.

**Comment by jepusto** [comment]
Hey @benthestatistician and @josherrickson, Turning to this now, and was wondering if I could get your opinion. `clubSandwich` has S3 methods for `vcovCR` that are adapted to the class of the model-object, so that different models will have different defaults for the arguments to `vcovCR`. For some types of models, it will make sensible guesses about the clustering variable so that it doesn't need to be specified explicitly. My question is: do you think it's useful to do the same thing for `meatCR`? Or would it reasonable to expect the user to provide explicit values for all the arguments? (In the absence of compelling arguments for the former, I'm going to go ahead with requiring explicit arguments for everything...)

**Comment by josherrickson** [comment]
I haven't looked extensively at your code, but I could see a scenario where it'd be easy to have `meatCR` replicate `vcovCR` in this context, or even have a generic `getDefaults` style function that both call internally. If that's the case (and it were my code and I had the time for it) I'd see no reason not to enable the same functionality.

That said, I'd think most users who would want the meat explicitly would be on the advanced end of things, so requiring explicit arguments for that would be entirely justifiable.

**Comment by jepusto** [comment]
That's an interesting suggestion but I'm not sure I see how I could do it through default options. What makes it tricky is that the behavior of vcovCR needs to depend on the class of the object to which it is applied. 

Anyways, I'll do the "advanced users only" version for now...

**Comment by jepusto** [comment]
So I ended up resolving this by adding a "form" argument to `vcovCR`. Specify `form = "meat"` to get the "paleo-style" sandwich with just the meat. For an arbitrary bread matrix `B` (of correct dimension), use `form = B`. 

```
data("Produc", package = "plm")
plm_state_year <- plm(log(gsp) ~ log(pcap) + log(pc) + log(emp) + unemp, 
                   data = Produc, index = c("state","year"), 
                   effect = "twoways", model = "within")

B <- sandwich::bread(plm_state_year)
M <- vcovCR(plm_state_year, cluster = "individual", type = "CR2", form = "meat")
n <- v_scale(plm_state_year)
BMB <- B %*% M %*% B / n
sndwch <- vcovCR(plm_state_year, cluster = "individual", type = "CR2")
identical(BMB, as.matrix(sndwch))
```

Let me know if this works for y'all.

**Comment by josherrickson** [comment]
Thanks @jepusto, this looks like it will address our needs. Appreciate the quick turn-around!
