### ISSUE TITLE
Non-nested random effect models

### ISSUE THREAD

**Issue by tqtbui** [jepusto/clubSandwich#94]
Hi James, 

This is a question, rather than an issue with the package. I was running a random effects model with a fixed effect for, say covariate X1, and a random effect for covariate X2. I'm wanting to get a clustered variance for clustering on X1. However, I encounter this error message: 

"Non-nested random effects detected. clubSandwich methods are not available for such models."

My questions are:
- Is there any reason that clustered variances work for nested random effects? Are the clustered variance formulas the same for nested random effect model as for the fixed effect model? Is there any reference paper that I can read about it? I have only been able to discover your paper on fixed effects model.
- What makes it impossible to apply clubSandwich methods for models with non-nested random effects?

Thank you and I'm looking forward to hearing from you.

**Comment by jepusto** [comment]
Hi @tqtbui sorry for not replying more quickly. 

> Is there any reason that clustered variances work for nested random effects?

The theory of CRVE and the small-sample corrections implemented in `clubSandwich` extend in a pretty straight-forward way to random effects models as long as the random effects have a hierarchically nested structure. One way to think about this is that such random effects models are a special case of generalized estimating equations, with a linear link function and maximum likelihood or restricted maximum likelihood estimators for the variance structure parameters. GEE has been studied pretty extensively, so it is a natural place to start.

> Are the clustered variance formulas the same for nested random effect model as for the fixed effect model?
No, but the fixed effect model can be understood as a special case of a random effect model (just one with a very simple error structure). So the general formulas apply to both, but the formulas for the fixed effect model simplify quite a bit. My [2018 paper with Beth Tipton](https://www.jepusto.com/publication/rve-in-fixed-effects-models/) gives the formulas for a very general case where:
1) the model includes fixed effects that are partialled out;
2) conditional on the fixed effects, the model has an error structure that is not necessarily homoskedastic and independent, so could still include hierarchical random effects terms; and
3) the model is estimated by weighted least squares with weights that can have off-diagonal terms (which would usually be inverse of the working model).
So I would suggest looking into that paper for details.

> Is there any reference paper that I can read about it? I have only been able to discover your paper on fixed effects model.
A good general reference on CRVE is [Cameron and Miller (2015)](https://jhr.uwpress.org/content/50/2/317.short).

> What makes it impossible to apply clubSandwich methods for models with non-nested random effects?

It is not necessarily impossible, it's just that the theory has not been worked out (as far as I know). The theory is also tricky ---trickier than the case with multi-way fixed effects---because the estimator for the regression coefficients doesn't have a simple form (it's weighted least squares but the weights are not block diagonal, so harder to analyze).
