### ISSUE TITLE
getGroups for lmerMod doesn't work.

### ISSUE THREAD

**Issue by spgarbet** [jepusto/clubSandwich#95]
When calling getGroups as per the documentation on an lmerMod class it fails because no S3 method is exported. 

```
> getGroups(model)
Error in UseMethod("getGroups") : 
  no applicable method for 'getGroups' applied to an object of class "c('lmerMod', 'merMod')"
> class(model)
[1] "lmerMod"
attr(,"package")
[1] "lme4"
```

Looking at the code this function appears like the cluster definition:

```
get_outer_group <- function(obj) {
  group_n <- lme4::getME(obj, "l_i")
  group_facs <- lme4::getME(obj, "flist")
  group_facs[[which.min(group_n)]]
}
```

Shouldn't this be as follows:

```
#' @export
lmerMod.getGroups <- function(object, form = formula(object), level=NULL, data=NULL, sep="/"){
  group_n <- lme4::getME(object, "l_i")
  group_facs <- lme4::getME(object, "flist")
  group_facs[[which.min(group_n)]]
}
```

Or alternatively export `get_outer_group` and update the documentation.

**Comment by spgarbet** [comment]
I can write a pull request if you have a preference.

**Comment by jepusto** [comment]
`getGroups()` is a generic specific to the structure of models from the `nlme` package. I don't think `get_outer_group()` works as a parallel method for `lmerMod` objects. I would prefer not to export `get_outer_groups()` because it is specific to `lmerMod`s and it presumes a hierarchical structure rather than checking for one. It's only three lines of code, so folks can roll their own.
